services:

  mysql:
    image: mysql:8.4
    container_name: notre-histoire-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notre_histoire
      MYSQL_USER: notre_histoire
      MYSQL_PASSWORD: notre_histoire

    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
